name: Check Spain ES in API

on:
  schedule:
    - cron: "*/3 * * * *" # cada 3 minuto aprox
  workflow_dispatch:

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener JSON de la API
        id: api
        run: |
            echo "🔍 Llamando a la API..."
            curl -s "https://upgrader.cc/API/?stock" > response.json
            echo "Response obtenida:"
            cat response.json
            # Guardar en output seguro
            echo "response<<EOF" >> $GITHUB_OUTPUT
            cat response.json >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT

      - name: Comprobar si existe Spain ES
        id: spain
        run: |
            # Filtrar Spain de manera segura
            spain=$(jq '.[] | select(.country_code=="ES")' response.json 2>/dev/null || echo "")
            echo "Resultado del filtro Spain ES:"
            echo "$spain"
            if [ -n "$spain" ]; then
                echo "found=true" >> $GITHUB_OUTPUT
                echo "spain_data<<EOF" >> $GITHUB_OUTPUT
                echo "$spain" >> $GITHUB_OUTPUT
                echo "EOF" >> $GITHUB_OUTPUT
            else
                echo "found=false" >> $GITHUB_OUTPUT
            fi

      - name: Enviar alerta a Telegram
        if: steps.spain.outputs.found == 'true'
        run: |
            echo "🚨 Spain ES encontrado, enviando alerta..."
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
              -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
              -d text="⚠️ ¡Spain ES detectado en la API!\n\n${{ steps.spain.outputs.spain_data }}"

      - name: Notificar si no se encontró Spain ES
        if: steps.spain.outputs.found == 'false'
        run: |
            echo "✅ Spain ES no se encontró en la API."
            
