name: Check Spain ES in API

on:
  schedule:
    - cron: "*/1 * * * *" # cada 5 minutos
  workflow_dispatch:       # también lo puedes ejecutar manualmente

jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener JSON de la API
        id: api
        run: |
          response=$(curl -s "https://upgrader.cc/API/?stock")
          echo "response=$response" >> $GITHUB_OUTPUT

      - name: Comprobar si existe Spain ES
        id: spain
        run: |
          spain=$(echo '${{ steps.api.outputs.response }}' | jq '.[] | select(.country_code=="ES")')
          if [ -n "$spain" ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            echo "spain_data=$spain" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Enviar alerta a Telegram
        if: steps.spain.outputs.found == 'true'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="⚠️ ¡Spain ES detectado en la API!\n\n${{ steps.spain.outputs.spain_data }}"
